#:schema node_modules/wrangler/config-schema.json
name = "bsky-post-curator-worker"
main = "src/index.js"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# Cron triggers
# Run every minute
[triggers]
crons = [ "* * * * *" ]

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
[[d1_databases]]
binding = "DB"
database_name = "bluesky-posts" 
database_id = "2de92ec5-dcf9-41bf-88f4-692d4e97e37f"